### ISSUE TITLE
Plans for support running as Azure Functions?

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#25]
Seems a good/great fit also, ex: reducing pool creation time, no need to stop clusters, only paying for actual resources used (no idle time). 
Would be great if the package enabled both scenarios.
https://github.com/thdeltei/azure-function-r

**Comment by brnleehng** [comment]
We are exploring the usage of Azure Functions.

**Comment by paselem** [comment]
We took a look at this and while it makes sense on the surface, a lot of the capabilities around scheduling, monitoring and failovers don't work well in our design. Now that we support running on docker, we will further investigate using Azure Container Instances as mentioned in #47. This will probably be a longer poll though since Azure Container Instances work very well in smaller numbers, but do not scale as quickly at large numbers as Azure Batch VMs natively.
