### ISSUE TITLE
cannot debug start tasks specified in cluster.json file

### ISSUE THREAD

**Issue by hmorzaria** [Azure/doAzureParallel#281]
Hi
I am trying to run an analysis in a cluster from R but using an external library. In my cluster.json (below) I indicate as a start task to install that library (cdo) and necessary dependencies. The cluster initializes correctly and works with an example.
However, the job that uses the external library fails, and stderr.txt indicates that it cannot find the library (cdo) or azcopy (I thought the Docker came with Azcopy)

What is the best way to debug package installation in the cluster?

I tried running
getClusterFile(cluster, "tvm-XXXXz", "stderr.txt", downloadPath = "~/pool-errors.txt")
but cannot get it to download locally. 

I am managing the cluster from a VM running R studio server

stderr.txt:
`running
  '/usr/local/lib/R/bin/R --slave --no-restore --no-save --no-environ --no-restore --no-site-file --file=/mnt/batch/tasks/workitems/job20180620193858/job-1/jobpreparation/wd/worker.R --args 1 1 0 stop'

Warning: namespace ‘foreach’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
sh: 1: azcopy: not found
sh: 1: azcopy: not found
sh: 1: ncbo: not found
sh: 1: azcopy: not found
Warning messages:
1: In system(paste("azcopy", "--source  https://XXXXXX.blob.core.windows.net/climatemodelsstatregrid",  :
  error in running command`

 

{
  "name": "batchanomaly1",
  "vmSize": "Standard_F2",
  "maxTasksPerNode": 1,
  "poolSize": {
    "dedicatedNodes": {
      "min": 1,
      "max": 19
    },
    "lowPriorityNodes": {
      "min": 1,
      "max": 9
    },
    "autoscaleFormula": "QUEUE"
  },
  "containerImage": "rocker/tidyverse:latest",
  "rPackages": {
    "cran": ["dplyr","tidyverse","raster"],
    "github": [],
    "bioconductor": []
  },
  "commandLine": [
  "apt-get install -y libnetcdf-dev libhdf5-dev",
  "apt-get install -y cdo nco"
  ],
  "subnetId": ""
}

**Comment by brnleehng** [comment]
Hi @hmorzaria 

I am able to repro the issue, downloading the file is not working. I will get a fix. In the meantime, you can 
cat the output and copy/save as a file

``` R
cat(getClusterFile(cluster, "tvm-680114044_1-20180620t182634z", "stderr.txt"))
```

Is CDO a R package? The issue is apt packages are being installed on the host, not on the docker image. 
If that's the case, you will need to build your own docker file.. and upload it. I will try to find one on docker hub with these apt packages with R

Thanks,
Brian

**Comment by hmorzaria** [comment]
Brian:
Thank you, I think the language in the documentation is confusing.  From document 30 customizing cluster:
"The commandline _property in the cluster configuration file allows users to prepare the nodes' environments. For example, users can perform actions such as installing applications that your foreach loop requires_."

Although it later does say "Note: All commands are run on the host node, not from within the container" that first section makes it confusing and it is hard to understand what the expected behavior should be.

CDO is a library to perform operations on climate data files, it installs as a linux package.

I will look for a Docker image that contains the libraries I need.

**Comment by brnleehng** [comment]
I'll update the documentation to be more accurate (Will add examples of when to use command line)

I've also been thinking about building a docker file locally on top of the container images on the VMs such as appending the commands from the configuration file.

We would attempt to create a dockerfile and upload it to each VM. Every VM would build it locally instead of pulling from dockerhub. This allows the user to not have to deal with uploading and creating their own docker files.

``` Dockerfile
FROM rocker/tidyverse:latest
RUN apt-get update && apt-get -y --no-install-recommends install \
        apt-get install -y libnetcdf-dev libhdf5-dev \
        apt-get install -y cdo nco
```

Let me know what are your thoughts 

Brian

**Comment by hmorzaria** [comment]
Brian:

I think from a user perspective your suggestion is certainly better, i.e. build the docker file locally including any needed commands. 
The only question is whether that introduces more chances for something to go wrong as each VM builds the dockerfile - I don't know enough about Docker.

**Comment by brnleehng** [comment]
Yeah,

Building a dockerfile locally can take upwards of 30 minutes.. So it might be best to create a Dockerfile then upload to Dockerhub.

Brian

**Comment by brnleehng** [comment]
Hi @hmorzaria 

Were you able to create your dockerfile? I've been researching for a R package that can build your dockerfile (http://o2r.info/2017/05/30/containerit-package/#22-packaging-an-interactive-session). 

If you have a sample code to reproduce, I can try to make a dockerfile through this R package.

Thanks,
Brian

**Comment by brnleehng** [comment]
Great to hear that!

We also support Azure Blob storage (https://github.com/Azure/doAzureParallel/tree/master/samples/sas_resource_files). I would recommend Azure blob storage because of performance and target throughput is much better than Azure File Share (60 MiB / per single share compared to 60 MiB per single blob).

There's a documentation about Azure storage limitations, [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets)

Thanks!
Brian
