### ISSUE TITLE
Reducing compute time

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#293]
Hello, I have a general question about Azure and doAzureParallel rather than a technical issue, but there's currently nowhere to ask such questions; perhaps a forum somewhere would be useful to discuss Azure and doAzureParallel in more general terms? Either way, apologies for asking such a question here but I hope that someone will be able to help.

I have a model to run which is itself comprised of two sub models. The first sub-model computes some aspect of climate and only needs to run once to generate climate estimates for the subsequent downstream analysis in the second sub-model. The second sub-model needs to access the output of the first sub-model and iterate 200 times, with the data from the first sub-model used as the input. I was wondering if this is possible using doAzureParallel?

I don't need the results of the first sub-model (the climate) to be returned to my local R Session, only the 200 iterations of the second sub-model. On pool deletion, I'm happy for the climate model results to be discarded. Really what I need to happen is for the first sub-model to run in Azure and then keep the generated object in the cloud, where it can then be accessed by the second sub-model. Is this is even possible? And, if so, how would the other nodes in the cluster be able to access this object?

My current approach is to run both sub-models together 200 times but in this way, I am unnecessarily running the first sub-model 199 more times than needed. If I could manage the alternative scenario described above, I could substantially reduce the processing time because the climate sub-model takes up more than half of the total processing time of both sub-models combined (each iteration of the full model takes about 0.5 seconds, 0.35 seconds of which is used by running the climate sub-model unnecessarily). Given that I have to run the full model many millions of times in total across the globe, shaving this 0.35 seconds off each iteration will be so useful in reducing the overall compute time. In fact, my analysis is probably impossible given my remaining grant funds without being able to resolve this.

In addition - would the Azure team recommend using fewer nodes in a cluster in order to improve merge times? For example, would it be better to have 32 x Standard_F16 or 8 x E64_v3 to get 512 cores? I feel that fewer machines will reduce overall processing time as there are fewer places from which to merge, even if the machines with more cores cost a little more per hour to run.

Thank you.

**Comment by darylmsft** [comment]
"Issues" can be questions so this use is great.  There _is_ a forum for Batch [here](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurebatch).   The forum covers all Batch topics so questions specific to doAzureParallel are a great fit here.

The pattern you describe of having the results of pre-calculations consumed by subsequent tasks is very much supported by Batch and Azure (Batch has a directed task graph, for example).  However, doAzureParallel does not (and cannot) expose all features of Azure or Batch so I'll get you specific answers from a team member.

On vm-size recommendations:   These optimizations are very much specific to individual customer needs but IF you get to persisting your outputs to some kind of storage (say, Azure Storage blobs for example) THEN you will need to manage the scale of the chosen persistence model.  In these cases, having fewer-but-bigger VMs is a benefit because you have fewer VMs pulling the required data.

d

**Comment by simon-tarr** [comment]
@brnleehng thanks very much for the detailed response. I have a few questions before I get started:

1. Should all the code above be happening within the same cluster? So wrap it in cluster <- `doAzureParallel::makeCluster("R/azure_credentials/cluster.json")` and finish with `doAzureParallel::stopCluster(cluster)`. Or in this particular method is the climate model set up independent of the second sub-model? i.e. the first part of the code is simply generating the climate data which can then be accessed by the second sub-model. I hope that makes sense!

2. I'm not quite following the code for the first sub-model. Sorry! Concerning the iterations within the first submodel: should this equal the number of nodes in the pool? In other words, am I running the climate sub-model once for every node that I wish the second sub-model to compute on? Or can I run it just once to generate the climate object? (In your example above the first sub-model iterates 3 times).

3. Within the second sub-model and to confirm my thinking: will the code `model <- download.url(storageFiles[i])` download the climate data and put it into the object `model` just the once, for the rest of the code to work on? Or will it download it for every iteration of the loop? I need to avoid the latter because the climate object is large and it will probably negate any performance increases from following this method.

4. Would I need to run some kind of clean up routine afterwards to delete the objects created by the first sub-model? I'll be running this process many times and it'll generate a lot of scratch data that I don't need to store permanently.

Thanks again.

**Comment by brnleehng** [comment]
1) It will download once for each iteration loop. If you don't want that experience, use resourceFiles as this will download the file once on each node, not on each task. 

If you needs all of the results of the first submodel, then I would recommend downloading it as a resource file. 

If you are using download.file function, you are downloading a specific resource file to one foreach loop. This will then load the downloaded file into the R session. We do spin up a new R session for each loop. 

- Does your second submodel iterations need all of the results of the first submodel? Or does it need a subset of the first submodel results?
- To clarify: You want the previous first submodel R environment session to be running for the second submodel. This will avoid the penalty of loading the first submodels every single time. Is this correct?

2) Yes, you will need to clean up the routine afterwards. You can use the deleteContainer function to delete the folder. 

3) Can you add the location of the credentials file that you generated? This will fix that issue since the value of the credentials is NULL

``` R 
# Get Storage Account Credentials
config <- rjson::fromJSON(file = paste0("FILE_PATH_OF_CREDENTIALS"))

storageCredentials <- rAzureBatch::SharedKeyCredentials$new(
  name = config$sharedKey$storageAccount$name,
  key = config$sharedKey$storageAccount$key
)
```

4)

> I have the option to run the climate (first sub-model) locally and simply upload this to my Azure storage. In many ways this is preferable because I am able to keep track of the other files in my workflow associated with the climate data. Given that I can upload this to storage and make it available on each node via the use of resource files, my question becomes the following:
> 
> Can I run a single line of code on each node that will put the object micro into my global environment in the R session? If so, the second sub-model will find the object and extract the data from it that it needs to finish the run. Perhaps I can use 'commandLine' within cluster.json? However, I'm not sure whether the resource files will be loaded prior to running a line of code saying to load micro into the global environment.

We upload a new R environment for every job creation. If you load the object micro on your local session and make a reference to micro in your second submodel forloop, the foreach package will auto detect this object and export it in the environment variable. The issue would be that you are paying for the upload and download of this object on a per job basis. 

The resource files will be downloaded before the commandLine parameters start. You can also use the resourceFiles parameter within cluster.json if you know the SAS token urls of the storage path. 


Thanks,
Brian

**Comment by simon-tarr** [comment]
Hi Brian, thanks once again for your help.

With regards to the bullet points in your Point 1 above, The second sub model doesn't need all of the points (I've expanded on this below). And yes, ideally, I just need the climate object floating about in the R environment.

In my use scenario, this is what I've been doing: I provide doAzureParallel with a locally held version of `coordinates`. Although it's a long list (n=67,000) it's a small object size-wise (<1MB) as it just contains x,y coordinates. The code works in series, running the function `micro_global` i times. On each iteration it creates an object called `micro` which is a dataframe of microclimatic conditions for that single x,y point in i. When the function `ectotherm` runs, it requires `micro` to be present.

```
results<-foreach(i = 1:nrow(coordinates), .options.azure = opt, .errorhandling = "pass") %dopar% {

  micro<-NicheMapR::micro_global(loc=coordinates[i,]) # Calculates climate at some x,y point in 'coordinates'

ecto<-ectotherm(soil = micro$soil) # This is the 'animal' model which requires 'micro'
results<-cbind(coordinates[i,1],coordinates[i,2],ecto$environ[,1:6], ecto$environ[,9:12], ecto$environ[,14]) # Binds a subset of the data in 'ecto' in order to reduce merging and downloading time etc.

}
```
As you can see, doAzureParallel does a fine job of dividing `coordinates` across nodes in the pool and then calculating the desired results. Ordinarily, this would be perfect (in fact, this is the procedure that I've been using for some previous work of mine). In my new project, however, I have hundreds of species that I need to analyse with the `ectotherm` sub-model using the exact same microclimate data. It therefore seems inefficient to continually calculate `micro` for each x,y coordinate for each species when the underlying microclimate data which feeds the `ectotherm` function doesn't change.

What I would love is for `micro` to be computed _once_ on each node and stay there until the pool is deleted. I can then run the `ectotherm` (second sub-model) n times, with n being the number of species I have to analyse. I could then end up with something like:

```
results<-foreach(i = 1:nrow(coordinates), .options.azure = opt, .errorhandling = "pass") %dopar% {
ecto<-ectotherm(soil = micro[[i]]$soil) # This is the 'animal' model which requires 'micro'
results<-cbind(coordinates[i,1],coordinates[i,2],ecto$environ[,1:6], ecto$environ[,9:12], ecto$environ[,14]) # Binds a subset of the data in 'ecto' in order to reduce merging and downloading time etc.
}
```

Regarding your Point 3, I have already included the path to my json file. All of the code works until I get to the line `readSasToken <- storageClient$generateSasToken(permission = "r", "c", path = job_name)`

Given our discussion so far, it seems like I probably can't do exactly what I need. Perhaps the best solution is to just run `micro_global` and `ectotherm` in series as I have been doing?

**Comment by brnleehng** [comment]
Yes, I think the best solution would be just running micro_global and ectotherm in a series then.

For the readSasToken, are you using the old credentials file without the sharedKey parameter?
