### ISSUE TITLE
Allow for local/external R workers to be part of doazure cluster/pool

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#37]
Don't know if this is possible, but would be nice to add our current free/available cores to the worker pool. Or join a local multi-node cluster to work on the same job/pool  (hybrid onprem/cloud cluster). 

similar scenario is possible with doRedis for example, as it's elastic & queue based, just calling startLocalWorkers(3,QUEUE_NAME,REDIS_HOST) I can add my cores to a onprem swarm r cluster

**Comment by paselem** [comment]
This is a very interesting feature request. As it stands now though, the backend we build on does not support a hybrid architecture and is currently not possible. There seems to be some effort in investigating this, but overall no concrete plans. Will close this for now since I realistically do not see a feasible solution in the short term.
