### ISSUE TITLE
Support for Azure Container Instances

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#47]
Think pretty much replaces my previous post regarding azure functions
seems a great combo! pay per use by the second, immediate startup/stop and probably easy to adapt

https://azure.microsoft.com/en-us/blog/announcing-azure-container-instances/

**Comment by paselem** [comment]
I like this idea! We are currently investigating support for containers as a high level concept to allow users to bring their own configurations.

Support of Azure Container Instances as the back-end may be a while out though since there is currently no native support for server-side scheduling or server-side clustering which are core to this tool for highly paralleled compute. As those features become available we will very much consider transitioning over.

**Comment by paselem** [comment]
After some investigation, support for Azure Containers Instances on Batch is likely not coming for a while. Wrangling many single instances is also not trivial at the moment. We will revisit this once we find a way to leverage ACI, but for now will close this.
